unverified:
- './*'
wontfix:
- any: ['./favicon.ico', './GothamRounded-**.*', './LICENSE', './README.md', './Screen*.webm', './Speedo.png', './_config.yml', './index.md', './404.md', '.github/*', '_includes/*', '.circleci/*', './CODE_OF_CONDUCT.md']
