title: My First Site
author: JavascriptLearner815
email: deanlovesmargie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first site. Come check it out!

# social links
github_username: JavascriptLearner815 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
