title: SpeedoThreeSixty Blog
author: JavascriptLearner815
email: deanlovesmargie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My first site. I'm a nerd. Also, please, PLEASE tell me you're not a dumb idiot that can't socially interact!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# social links
# DO NOT include the @ character, or else the build will fail!
twitter_username: DeanSummer3
github_username: JavascriptLearner815
youtube_username: channel/UC6spikDcAKWABZqw7nSLNKw
twitch_username: speedothreesixty
discord_username: SpeedoThreeSixty#3179

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
